name: Continuous Integration
on:
  push:
    branches:
      - main

jobs:
  build:
    name: Generate PDFs
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - uses: xu-cheng/latex-action@v2
        with:
          latexmk_use_lualatex: true
          # TODO ↓
          glob_root_file: true
          root_file: "TuS/*.tex"
      - uses: actions/upload-artifact@v2
        with:
          name: PDF
          path: ./main.pdf
      - name: Extract PDFs for bundling
        run: mkdir gh-pages-bundle && rsync -a --prune-empty-dirs --include '*.pdf' --exclude '*' ./ gh-pages-bundle/
      - name: Deploy 🚀
        uses: JamesIves/github-pages-deploy-action@v4
        with:
          branch: gh-pages
          folder: gh-pages-bundle
          clean: true
