name: Continuous Integration
on:
  push:
    branches:
      - main

jobs:
  build:
    name: Generate PDFs
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - name: Compile LaTex to PDFs
        uses: xu-cheng/latex-action@v2
        with:
          latexmk_use_lualatex: true
          # TODO ↓
          glob_root_file: true
          root_file: "TuS/*.tex"
      - name: Generate MD pages
        run: |
          sudo apt-get install pandoc
          find TuS -name '*.tex' -exec pandoc {} -o {}.md \;
      - name: Extract files for gh-pages
        run: mkdir gh-pages-bundle && rsync -a --prune-empty-dirs --include '*.pdf' --include '*.md' --exclude '*' ./ gh-pages-bundle/
      - name: Generate index
        run: sudo apt-get install tree && cd gh-pages-bundle && tree -H . > index.html
      - name: Setup tmate session
        uses: mxschmitt/action-tmate@v3
      - name: Deploy 🚀
        uses: JamesIves/github-pages-deploy-action@v4
        with:
          branch: gh-pages
          folder: gh-pages-bundle
          clean: true
